# Generated by Django 3.2.4 on 2021-06-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(unique_for_date=True)),
                ('end_date', models.DateField(unique_for_date=True)),
            ],
        ),
    ]
