# Generated by Django 3.2.4 on 2021-06-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0002_rename_number_sprint_sprint_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(),
        ),
    ]
