# Generated by Django 3.2.4 on 2021-06-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0003_auto_20210629_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(unique=True),
        ),
    ]
