# Generated by Django 3.2.4 on 2021-06-30 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0004_auto_20210629_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_number', models.IntegerField(primary_key=True, serialize=False)),
                ('planned', models.BooleanField(default=True)),
                ('added', models.BooleanField(default=False)),
                ('db_issue', models.BooleanField(default=False)),
                ('research', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('duplicated', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact.sprint')),
            ],
        ),
    ]
