# Generated by Django 3.2.4 on 2021-06-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_url',
            field=models.TextField(default='None', unique=True),
        ),
    ]
