# Generated by Django 3.2.4 on 2021-06-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0007_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='task_type',
            field=models.CharField(max_length=15),
        ),
    ]
