# Generated by Django 3.2.4 on 2021-06-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0012_alter_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
