# Generated by Django 3.2.4 on 2021-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0016_task_delivered_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_type', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
