# Generated by Django 3.2.4 on 2021-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0018_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delivered_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
