# Generated by Django 3.2.4 on 2021-06-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0019_alter_task_delivered_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delivered_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
