# Generated by Django 3.2.4 on 2021-06-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0020_alter_task_delivered_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cancelled',
            new_name='cancelled_resolved',
        ),
    ]
