# Generated by Django 3.2.4 on 2021-07-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0021_rename_cancelled_task_cancelled_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr',
            name='task',
        ),
        migrations.AddField(
            model_name='pr',
            name='task',
            field=models.ManyToManyField(to='fact.Task'),
        ),
    ]
