# Generated by Django 3.2.4 on 2021-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0023_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
