# Generated by Django 3.2.4 on 2021-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0026_pr_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='send_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
