# Generated by Django 3.2.4 on 2021-07-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0027_pr_send_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
