# Generated by Django 3.2.4 on 2021-07-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0030_pr_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
