# Generated by Django 3.2.4 on 2021-07-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0032_alter_pr_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='test',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
